// Generated by CoffeeScript 1.8.0
(function() {
  var GetAnswer, g, url;

  GetAnswer = require('../server/getAnswers');

  url = 'https://api.zhihu.com/answers/27770694';

  g = new GetAnswer(url);

  g.getContent();

}).call(this);

//# sourceMappingURL=getAnswer.js.map
