// Generated by CoffeeScript 1.8.0
(function() {
  var async, cookie, m, monit, noteStore, url;

  monit = require('../server/monitor');

  cookie = process.env.ZhiHu;

  noteStore = require('../server/noteStore');

  async = require('async');

  url = 'http://www.zhihu.com/collection/29469118';

  m = new monit(url, noteStore, cookie);

  async.series([
    function(cb) {
      console.log("here");
      return m.getLogPage(function(err) {
        if (err) {
          return console.log(err);
        }
        return cb();
      });
    }, function(cb) {
      var $;
      $ = m.$;
      return m.checkFav($, function(err) {
        if (err) {
          return console.log(err);
        }
        return cb();
      });
    }
  ]);

}).call(this);

//# sourceMappingURL=test-monit.js.map
