// Generated by CoffeeScript 1.8.0
(function() {
  var GetCol, g, url;

  GetCol = require('../server/getCollection');

  url = 'https://api.zhihu.com/collections/21437665/';

  g = new GetCol(url);

  g.getColList();

}).call(this);

//# sourceMappingURL=test-getcol.js.map
