// Generated by CoffeeScript 1.8.0
(function() {
  var cookie, noteStore, queue, url;

  queue = require('../server/queue');

  noteStore = require('../server/noteStore');

  cookie = process.env.ZhiHu;

  url = 'http://www.zhihu.com/question/29852397/answer/46153324';

  queue.push(url, noteStore, cookie, function(err) {
    if (err) {
      return console.log(err);
    }
  });

}).call(this);

//# sourceMappingURL=test-queue.js.map
