// Generated by CoffeeScript 1.8.0
(function() {
  var cookie, noteStore, queue, url1, url2, url3;

  queue = require('../server/queue');

  noteStore = require('../server/noteStore');

  cookie = process.env.ZhiHu;

  url1 = 'http://www.zhihu.com/question/22896560/answer/44790537';

  url2 = 'http://www.zhihu.com/question/23854296/answer/25906136';

  url3 = 'http://www.zhihu.com/question/27971326/answer/45822583';

  queue.push({
    url: url1,
    noteStore: noteStore,
    cookie: cookie
  }, function(err) {
    if (err) {
      return console.log(err);
    }
  });

}).call(this);

//# sourceMappingURL=test-queue.js.map
