// Generated by CoffeeScript 1.8.0
(function() {
  var Evernote, async, cheerio, cookie, makeNote, noteStore, op, reqOp, request;

  request = require('request');

  async = require('async');

  cookie = process.env.ZhiHu;

  cheerio = require('cheerio');

  makeNote = require('./server/createNote');

  noteStore = require('./server/noteStore');

  Evernote = require('evernote').Evernote;

  reqOp = function(url) {
    var options;
    options = {
      url: url,
      headers: {
        'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36',
        'Cookie': cookie
      }
    };
    return options;
  };

  op = reqOp('http://www.zhihu.com/collection/29469118');

  request.get(op, function(err, res, body) {
    var $, $2, answerList, content1, content2, content3, title;
    if (err) {
      return console.log(err);
    }
    $ = cheerio.load(body);
    answerList = $("#zh-list-answer-wrap > div");
    $ = cheerio.load(answerList[0]);
    title = $("h2.zm-item-title").text();
    content1 = $(".content.hidden").text().replace(/<br>/g, '</br>');
    console.log(content1);
    $2 = cheerio.load(content1);
    $2("a, span").removeAttr("class").removeAttr("href");
    content2 = $2.html();
    console.log(content2);
    content3 = "<img src='http://pic3.zhimg.com/31fa9c0fdbe89aa0464c1110cc3c0382_r.jpg'/>";
    return makeNote(noteStore, title, content3, 'http://www.zhihu.com/collection/29469118', function(err1, note) {
      if (err1) {
        return console.log(err1);
      }
      return console.log(note);
    });
  });

}).call(this);

//# sourceMappingURL=app.js.map
