// Generated by CoffeeScript 1.8.0
(function() {
  var Collections, async, express, router;

  express = require('express');

  router = express.Router();

  async = require('async');

  Collections = require('../models/collections');

  router.get('/', function(req, res) {
    var username;
    username = req.session.username;
    return Collections.find({
      username: username
    }, function(err, rows) {
      if (err) {
        return console.log(err);
      }
      return console.log(rows);
    });
  });

  router.get('/add/:url', function(req, res) {
    var url, username;
    username = req.session.username;
    url = req.params.url;
    return async.auto({
      checkExits: function(cb) {
        return Collections.findOne({
          url: url
        }, function(err, row) {
          if (err) {
            return console.log(err);
          }
          if (row) {
            return res.send("aleary exits this url:" + url);
          } else {
            return cb();
          }
        });
      },
      addUrl: [
        'checkExits', function(cb) {
          var col;
          col = new Collection();
          col.username = username;
          col.url = url;
          col.created = Date.now();
          col.type = 1;
          return col.save(function(err, row) {
            if (err) {
              return console.log(err);
            }
            return res.send("add ok");
          });
        }
      ]
    });
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=collection.js.map
