// Generated by CoffeeScript 1.8.0
(function() {
  var ClientLogin, requrest;

  requrest = require('request');

  ClientLogin = (function() {
    function ClientLogin(params) {
      this.params = params;
    }

    ClientLogin.prototype.login = function() {
      var op, self;
      self = this;
      op = {
        url: self.params.url,
        headers: {
          'User-Agent': 'osee2unifiedRelease/332 (iPad; iOS 8.3; Scale/2.00)'
        },
        form: self.params
      };
      return requrest.post(op, function(err, res, body) {
        if (err) {
          return console.log(err);
        }
        return console.log(body);
      });
    };

    return ClientLogin;

  })();

  module.exports = ClientLogin;

}).call(this);

//# sourceMappingURL=clientLogin.js.map
