// Generated by CoffeeScript 1.8.0
(function() {
  var Evernote, makeNote;

  Evernote = require('evernote').Evernote;

  makeNote = function(noteStore, noteTitle, noteBody, sourceUrl, parentNotebook, callback) {
    var attr, nBody, ourNote;
    nBody = '<?xml version="1.0" encoding="UTF-8"?>';
    nBody += '<!DOCTYPE en-note SYSTEM "http://xml.evernote.com/pub/enml2.dtd">';
    nBody += '<en-note>' + noteBody + '</en-note>';
    ourNote = new Evernote.Note;
    attr = new Evernote.NoteAttributes;
    attr.sourceURL = sourceUrl;
    ourNote.title = noteTitle;
    ourNote.content = nBody;
    ourNote.attributes = attr;
    if (parentNotebook && parentNotebook.guid) {
      ourNote.notebookGuid = parentNotebook.guid;
    }
    return noteStore.createNote(ourNote, function(err, note) {
      if (err) {
        return console.log(err);
      } else {
        return callback(note);
      }
    });
  };

  module.exports = makeNote;

}).call(this);

//# sourceMappingURL=createNote.js.map
