// Generated by CoffeeScript 1.8.0
(function() {
  var GetAnswer, request;

  request = require('request');

  GetAnswer = (function() {
    function GetAnswer(url) {
      this.url = url;
      this.headers = {
        'User-Agent': 'osee2unifiedRelease/332 CFNetwork/711.3.18 Darwin/14.0.0',
        'Authorization': 'oauth 5774b305d2ae4469a2c9258956ea49',
        'Content-Type': 'application/json'
      };
    }

    GetAnswer.prototype.getContent = function() {
      var op, self;
      self = this;
      op = {
        url: self.url,
        headers: self.headers
      };
      return request.get(op, function(err, res, body) {
        var data;
        if (err) {
          return console.log(err);
        }
        data = JSON.parse(body);
        return console.log(data);
      });
    };

    return GetAnswer;

  })();

  module.exports = GetAnswer;

}).call(this);

//# sourceMappingURL=getAnswers.js.map
