// Generated by CoffeeScript 1.8.0
(function() {
  var Evernote, client, noteStore;

  Evernote = require('evernote').Evernote;

  client = new Evernote.Client({
    token: developerToken
  });

  noteStore = client.getNoteStore('https://sandbox.evernote.com/shard/s1/notestore');

  module.exports = noteStore;

}).call(this);

//# sourceMappingURL=noteStore.js.map
