// Generated by CoffeeScript 1.8.0
(function() {
  var ReTask, Task, async, queue;

  Task = require('../models/task');

  queue = require('../server/getAnswers');

  async = require('async');

  ReTask = (function() {
    function ReTask() {}

    ReTask.prototype.resume = function() {
      return async.auto({
        findTask: function(callback) {
          return Task.find({
            $or: [
              {
                status: 0
              }, [
                {
                  status: 1
                }
              ]
            ]
          }, function(err, rows) {
            if (err) {
              return console.log(err);
            }
            return callback(null, rows);
          });
        },
        addTask: [
          'findTask', function(callback, result) {
            var taskArr;
            taskArr = result.findTask;
            return taskArr.forEach(function(task) {
              return queue.push({
                url: task.url,
                noteStore: self.noteStore
              }, function(err) {
                return Task.findOne({
                  url: task.url
                }, function(err2, row) {
                  if (err2) {
                    return console.log(err2);
                  }
                  if (err) {
                    return console.log(err);
                  } else {
                    return self.changeStatus(task.url, 4, cb);
                  }
                });
              });
            });
          }
        ]
      });
    };

    return ReTask;

  })();

}).call(this);

//# sourceMappingURL=reTask.js.map
