// Generated by CoffeeScript 1.8.0
(function() {
  var CollectionsSchema, mongoose;

  mongoose = require('./mongoose');

  CollectionsSchema = mongoose.Schema({
    username: String,
    created: Number,
    type: Number,
    url: String
  });

  module.exports = mongoose.model('Collections', CollectionsSchema);

}).call(this);

//# sourceMappingURL=collections.js.map
