// Generated by CoffeeScript 1.8.0
(function() {
  var ErrLogSchema, mongoose;

  mongoose = require('./mongoose');

  ErrLogSchema = mongoose.Schema({
    title: String,
    created: Number,
    href: String,
    type: Number,
    info: String
  });

  module.exports = mongoose.model('ErrLog', ErrLogSchema);

}).call(this);

//# sourceMappingURL=err-log.js.map
