// Generated by CoffeeScript 1.8.0
(function() {
  var SyncLogSchema, mongoose;

  mongoose = require('./mongoose');

  SyncLogSchema = mongoose.Schema({
    title: String,
    content: String,
    created: Number,
    updated: Number,
    tagNames: Array,
    href: String
  });

  module.exports = mongoose.model('SyncLog', SyncLogSchema);

}).call(this);

//# sourceMappingURL=sync-log.js.map
