// Generated by CoffeeScript 1.8.0
(function() {
  var UserSchema, mongoose;

  mongoose = require('./mongoose');

  UserSchema = mongoose.Schema({
    name: String,
    created: Number,
    token: String,
    type: Number,
    info: String
  });

  module.exports = mongoose.model('User', UserSchema);

}).call(this);

//# sourceMappingURL=user.js.map
